name: Tests

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v22.11.0' 

      - name: Install dependencies
        run: |
          npm install  

      - name: Run tests with coverage
        run: npm test -- --coverage || exit 0 # This ensures Coveralls runs even if previous steps have failed

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}